name: agrismart_flutter
description: "AgriSmart ESP32 - Flutter Precision Field Telemetry & Remote Controls Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.2.0
  web_socket_channel: ^2.4.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
